# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 510097f0e5995f31506be6a90c86cf29287c8d24d448c6aaee055770d7621d31d2d188fe98ba957061f63e7debdccdd3d868f1b499e9710f68195c31c5f61821

test:
  secret_key_base: 5c7338b81d5dd759c44c13e6fc76dbef521e81862ac412843e1179b7bce00faa211981e840b1d79bcb7815c56eae764ce1a87d5ec6193a944f3c17a701e91251

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
